### PR TITLE
Update sanitizeShellInput.js

### PR DESCRIPTION
**Pull request by qaraluch**
See Issue no #13

### CODE REVIEW

**Comment by krzkaczor** [comment]
Looks good, can you write some tests covering this case?

**Comment by qaraluch** [comment]
Done. Tests was rather straightforward. The root of the problem was misleading `const endOfLine = require('os').EOL` in case of running it in both environments (WSL).

**Comment by qaraluch** [comment]
@krzkaczor ping

**Comment by krzkaczor** [comment]
I need to test it properly and check all other changes (`standard` dep etc). It will be done during the weekend ;)

**Comment by qaraluch** [comment]
a lot of work heh? ;) sure ...

**Comment by krzkaczor** [comment]
Hey, thanks for contribution. Sorry that it took so long. 18 days... could be worse I guess ;)

**Pull request merged**
